### ISSUE TITLE
rsp error

### ISSUE THREAD

**Issue by leapar** [hasherezade/IAT_patcher#4]
window 10 hook api crash！！！

1、
![image](https://user-images.githubusercontent.com/5162637/131431350-ccc84fb7-d72e-4fd8-9649-8e25fa5416de.png)

0x00007FF737D20A34
is the pre main function

2、
![image](https://user-images.githubusercontent.com/5162637/131431401-7c851a01-04b7-4123-80ac-38f667e0404b.png)

0x00007FF73AD01013
to jmp the main function

3、jmp function in the stack will be changed
![image](https://user-images.githubusercontent.com/5162637/131431522-6af01983-b243-4b8a-971c-9c42f3c0e5ed.png)

4、has been changed
![image](https://user-images.githubusercontent.com/5162637/131431610-857f420d-be57-4200-828e-30ae7d6f12f3.png)
00007FF73AD010A0  should be  0x00007FF73AD01013

5、will go to error rsp
![image](https://user-images.githubusercontent.com/5162637/131431714-0155e3cf-fe40-4d3a-b3f2-6d5da11866d8.png)

**Comment by hasherezade** [comment]
Hi, in which circumstances did the crash happened? Did it happened on return from your replacement function?

Are you sure that the function that you used as a replacement has **exactly the same API** as the function that you was hooking? Not only parameter numbers and types have to match, but also the **calling convention has to be identical** ( i.e. `_stdcall` function cannot be use as a replacement of  `_cdecl` function, and vice versa).
It there is mismatch, the return will not be good.

**Comment by leapar** [comment]
yes!
i am sure!
i modify the asm like this,it test ok!
i am not sure it will work well all of windows version!

![image](https://user-images.githubusercontent.com/5162637/131474184-77515fa5-b9a5-48e6-8985-b38a01c3d73c.png)

**Comment by leapar** [comment]
and also  there has a bug in the hexf.cpp  file.
i build the asm by yasm, and there has 0xff code, the hexf.cpp will break,so when i copy these code to stubdata.h it will be error!
and i modify this file like this.

![image](https://user-images.githubusercontent.com/5162637/131475034-f2081bd8-3580-4a82-a244-92660769cdd8.png)

**Comment by hasherezade** [comment]
Ah, now I understand what you mean... So it is a bug in the stub. It is my old code and it wasn't tested on Windows 10.
Thank you for fixing, feel free to send me a pull request. I will test if it works on other Windows versions too.

**Comment by leapar** [comment]
#5

**Comment by hasherezade** [comment]
Thank you for your contribution, the new release is ready:
https://github.com/hasherezade/IAT_patcher/releases/tag/v0.3.5.4

**Comment by leapar** [comment]
thank you for your project. 
it saves my time.
