### ISSUE TITLE
Possible to hook DllMain?

### ISSUE THREAD

**Issue by brandonros** [hasherezade/IAT_patcher#6]
I want to make sure a DLL I have gets injected pretty much "on process load"  / "before the process starts executing".

**Comment by hasherezade** [comment]
I am sorry, but this app does IAT hooking only, which means, only functions that are in the Import Table can be replaced within the hooked executable. From what you are saying it seems that you need inline hooking (of the `DllMain` within the DLL to be injected), not IAT hooking (of the target exe), which is a different hooking model (_*the details on the difference between IAT hooking and inline hooking was explained here: https://github.com/hasherezade/malware_training_vol1/blob/main/slides/module2/Module2_2_hooking.pdf_).

**Comment by brandonros** [comment]
Thanks for clarifying. This app I have can tell when it's IAT table has been patched and doesn't like when you attach debuggers.

You have to attach a debugger to do inline hooking, right?

I was thinking more like, hooking DllMain of kernel32? Or replacing the IAT of a system module that requires kernel32, without having to mock the entire kernel32 DLL with hooks
